# Generated by Django 3.1.4 on 2020-12-13 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('nombre_ciudad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Humedad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Temperatura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Calor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Concentracion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('SensorHumo', models.CharField(max_length=1)),
                ('SensorMetano', models.CharField(max_length=1)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
                ('Ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dato.ubicacion')),
            ],
        ),
    ]
