# Generated by Django 3.1.4 on 2020-12-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='SensorHumo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datos',
            name='SensorMetano',
            field=models.BooleanField(default=False),
        ),
    ]
