# Generated by Django 3.1.4 on 2021-01-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dato', '0002_auto_20201214_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='Ubicacion',
        ),
        migrations.AddField(
            model_name='datos',
            name='Latitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='datos',
            name='Longitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='datos',
            name='Calor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='datos',
            name='Concentracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='datos',
            name='Humedad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='datos',
            name='Temperatura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
