# Generated by Django 3.1.4 on 2021-01-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dato', '0003_auto_20210108_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='Latitud',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='datos',
            name='Longitud',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
    ]
